[package]
name = "mdbook-latex"
version = "0.1.24"
authors = ["lbeckman314 <liam@liambeckman.com>"]
edition = "2018"
description = "An mdbook backend for generating LaTeX and PDF documents."
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/lbeckman314/mdbook-latex"

[dependencies]
mdbook = "0.3.5"
serde = "1.0.104"
serde_derive = "1.0.104"
tectonic = "0.1.12"
md2tex = "0.1.3"

[profile.release]
panic = "abort"

